<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Pictures\black-hole.png" />
    <None Remove="Pictures\ForumLogo.png" />
    <None Remove="Pictures\galaxy.png" />
    <None Remove="Pictures\Helmet.png" />
    <None Remove="Pictures\ISS.png" />
    <None Remove="Pictures\Landing.png" />
    <None Remove="Pictures\Logo.png" />
    <None Remove="Pictures\mars.png" />
    <None Remove="Pictures\NASA.png" />
    <None Remove="Pictures\planet.png" />
    <None Remove="Pictures\rocket.png" />
    <None Remove="Pictures\satellite.png" />
    <None Remove="Pictures\sparkling.png" />
    <None Remove="Pictures\stars.png" />
    <None Remove="Pictures\stars1.png" />
    <None Remove="Pictures\ufo %281%29.png" />
    <None Remove="Pictures\ufo %282%29.png" />
    <None Remove="Pictures\ufo.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="3.2.0" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3967.48" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SpaceServer\SpaceServer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Pictures\black-hole.png" />
    <Resource Include="Pictures\galaxy.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Pictures\background.png" />
    <Resource Include="Pictures\ForumLogo.png" />
    <Resource Include="Pictures\Helmet.png" />
    <Resource Include="Pictures\ISS.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Pictures\Landing.png" />
    <Resource Include="Pictures\Logo.png" />
    <Resource Include="Pictures\mars.png" />
    <Resource Include="Pictures\NASA.png" />
    <Resource Include="Pictures\planet.png" />
    <Resource Include="Pictures\rocket.png" />
    <Resource Include="Pictures\satellite.png" />
    <Resource Include="Pictures\sparkling.png" />
    <Resource Include="Pictures\stars.png" />
    <Resource Include="Pictures\stars1.png" />
    <Resource Include="Pictures\ufo (1).png" />
    <Resource Include="Pictures\ufo (2).png" />
    <Resource Include="Pictures\ufo.png" />
  </ItemGroup>

  <ItemGroup>
    <None Update=".env">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ISS\ISS_map.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ISS\script.js">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ISS\style.css">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
